---
# Playbook principal : Configuration complÃ¨te de la VM

- name: Configure VM and deploy application
  hosts: vm
  become: yes
  gather_facts: yes
  
  roles:
    - bootstrap
    - docker
    - app
    - nginx  # ðŸ‘ˆ AJOUT du rÃ´le nginx